Repository Minifood-Hub/Minifood-FE, pull requests merged in 2024-09, with the labels that each got.

#41 ✨[FAQ/공지사항, 거래처]: 자주 묻는 질문/공지사항 페이지 작성, 거래처 주소 검색 추가
  package-lock.json
  package.json
  src/app/(route)/faq/page.tsx
  src/app/(route)/notice/page.tsx
  src/app/_types/sign-in.ts
  src/app/components/admin/AdminHeader.tsx
  src/app/components/admin/faq/FAQPut.tsx
  src/app/components/admin/notices/NoticePut.tsx
  src/app/components/common/ClientInfoModal.tsx
  src/app/components/common/Pagination.tsx
  src/app/components/common/ProfileDropDown.tsx
  src/app/components/faq/DetailFAQ.tsx
  src/app/components/faq/FAQSideBar.tsx
  src/app/components/faq/container/FrequentFAQContainer.tsx
  src/app/components/main/Information.tsx/Announcement.tsx
  src/app/components/main/Information.tsx/Question.tsx
  src/app/components/notice/DetailNotice.tsx
  src/app/components/notice/container/NoticeContainer.tsx
  src/app/components/quotation/modal/view/QuotationTable.tsx
  src/app/components/sign-in/client/AddressModal.tsx
  src/app/components/sign-in/client/ClientComponents.tsx
  src/app/components/sign-in/client/EditClientComponents.tsx
  src/app/components/sign-in/common/SignInButton.tsx
  src/app/components/sign-in/common/SignInInput.tsx
  src/app/constants/faq.ts
  src/app/constants/notice.ts
  src/app/constants/sign-in.ts
  src/app/ui/iconPath.ts
Labels: feat, 현중

#44 :recycle: [공통] : UI수정 및 예외처리
  src/app/components/common/layout/Header.tsx
Labels: 민규, recycle

#43 ✨[관리자]: 관리자 수정
  src/app/_types/order.ts
  src/app/api/account/password/route.ts
  src/app/components/account/AccountCertificate.tsx
  src/app/components/account/AccountUpdate.tsx
  src/app/components/admin/AdminHeader.tsx
  src/app/components/admin/clients/ClientsName.tsx
  src/app/components/admin/clients/ClientsRegion.tsx
  src/app/components/admin/container/ProductsContainer.tsx
  src/app/components/admin/faq/FAQPost.tsx
  src/app/components/admin/faq/FAQPut.tsx
  src/app/components/admin/notices/NoticePost.tsx
  src/app/components/admin/notices/NoticePut.tsx
  src/app/components/admin/products/ProductsCategory.tsx
  src/app/components/admin/products/ProductsCreate.tsx
  src/app/components/admin/products/ProductsUpload.tsx
  src/app/components/admin/products/ProductsVegetable.tsx
  src/app/components/admin/products/ProductsVegetableFile.tsx
  src/app/components/admin/quotations/Info.tsx
  src/app/components/common/ClientInfoModal.tsx
  src/app/components/common/Dialog.tsx
  src/app/components/common/ProfileDropDown.tsx
  src/app/constants/account.ts
  src/app/constants/admin.ts
  src/app/constants/common.ts
Labels: 현중, recycle

#47 :sparkles: [공통] 회의후피드백
  package-lock.json
  package.json
  public/Images/JMF1.png
  public/Images/JMF3.png
  public/Images/favicon.png
  public/Images/logo.png
  public/Images/mainImage.jpg
  public/Images/maintest2.jpg
  public/Images/reorder.jpg
  public/favicon.ico
  src/app/(route)/layout.tsx
  src/app/(route)/page.tsx
  src/app/(route)/pastorder/new/page.tsx
  src/app/(route)/test/page.tsx
  src/app/_types/order.ts
  src/app/components/main/container/InformationContainer.tsx
  src/app/components/order/ProductItem.tsx
  src/app/components/order/ProductList.tsx
  src/app/components/pastorder/PastOrderTableInfo.tsx
  src/app/components/pastorder/PastorderTable.tsx
  src/app/components/pastorder/container/NewPastOrderContainer.tsx
  src/app/components/pastorder/container/PastorderContainer.tsx
  src/app/components/quotation/QuotationViewTable.tsx
  src/app/components/quotation/QuotationViewTableInfo.tsx
  src/app/components/quotation/container/EditQuoteContainer.tsx
  src/app/components/quotation/modal/edit/EditQuotationModal.tsx
  src/app/constants/alert.ts
  src/app/constants/pastorder.ts
  src/app/constants/quotation.ts
  src/app/static/fonts/PretendardVariable.woff2
  src/app/ui/Icons/Logo.tsx
  src/app/ui/globals.css
  src/app/ui/iconPath.ts
  src/app/utils/toast.ts
  src/app/utils/useStore.ts
  tailwind.config.ts
Labels: feat, 민규

#49 ✨[공통]: 마무리 작업
  src/app/(route)/pastorder/page.tsx
  src/app/(route)/product/page.tsx
  src/app/(route)/quotation/edit/[id]/page.tsx
  src/app/(route)/quotation/page.tsx
  src/app/api/account/refresh/route.ts
  src/app/components/admin/AdminHeader.tsx
  src/app/components/admin/clients/ClientsName.tsx
  src/app/components/admin/clients/ClientsRegion.tsx
  src/app/components/admin/clients/EntireClients.tsx
  src/app/components/admin/faq/FAQGet.tsx
  src/app/components/admin/notices/NoticeGet.tsx
  src/app/components/common/layout/Header.tsx
  src/app/components/common/layout/SideNavBar.tsx
  src/app/components/order/ProductList.tsx
  src/app/components/order/container/OrderContainer.tsx
  src/app/components/pastorder/PastorderTable.tsx
  src/app/hooks/useResponsiveHeight.tsx
  src/app/service/postRequest.ts
  src/app/utils/date.ts
  src/app/utils/setTokens.ts
Labels: feat, 현중

#57 ♻[공통]: Next.js 14 버전 14.2.4 -> 14.2.13으로 업데이트
  package-lock.json
  package.json
Labels: 현중, recycle
