Repository Minifood-Hub/Minifood-FE, pull requests merged in 2024-08, with the labels that each got.

#17 ✨ [견적서,주문내역] UI제작
  .eslintrc.json
  package-lock.json
  package.json
  public/Images/JMF1.png
  public/Images/JMF2.png
  public/Images/JMF3.png
  public/Images/mainImage.jpg
  src/app/(route)/page.tsx
  src/app/(route)/quotation/page.tsx
  src/app/(route)/test/modal/page.tsx
  src/app/(route)/test/page.tsx
  src/app/_types/order.ts
  src/app/_types/quotation.ts
  src/app/api/quotation/delete/route.ts
  src/app/api/quotation/detail/route.ts
  src/app/api/quotation/route.ts
  src/app/components/common/Button.tsx
  src/app/components/common/Pagination.tsx
  src/app/components/common/layout/Footer.tsx
  src/app/components/common/layout/Header.tsx
  src/app/components/common/layout/SideNavBar.tsx
  src/app/components/main/Welcome.tsx
  src/app/components/quotation/QuotationViewTable.tsx
  src/app/components/quotation/QuotationViewTableInfo.tsx
  src/app/components/quotation/container/QuotationContainer.tsx
  src/app/components/quotation/modal/DeleteQuotationModal.tsx
  src/app/components/quotation/modal/QuotationModal.tsx
  src/app/components/quotation/modal/QuotationTable.tsx
  src/app/constants/common.ts
  src/app/constants/quotation.ts
  src/app/constants/styles.ts
  src/app/constants/test.ts
  src/app/hooks/useModal.ts
  src/app/service/deleteRequest.ts
  src/app/service/getRequest.ts
  src/app/ui/iconPath.ts
  src/app/utils/callApi.ts
  src/app/utils/date.ts
Labels: feat, 민규

#19 ✨[견적서_주문] 견적서 주문 모달 작성
  package-lock.json
  package.json
  src/app/(route)/order/page.tsx
  src/app/_types/order.ts
  src/app/_types/sign-in.ts
  src/app/api/order/quotations/[quotation_id]/confirmation/route.ts
  src/app/api/order/quotations/[quotation_id]/particulars/route.ts
  src/app/api/order/quotations/[quotation_id]/total/route.ts
  src/app/api/order/quotations/products/route.ts
  src/app/api/order/quotations/route.ts
  src/app/api/order/search/route.ts
  src/app/api/order/users/route.ts
  src/app/components/common/Dialog.tsx
  src/app/components/common/Loading.tsx
  src/app/components/order/ProductItem.tsx
  src/app/components/order/ProductList.tsx
  src/app/components/order/container/OrderContainer.tsx
  src/app/components/order/quotation/OrderQuotationModal.tsx
  src/app/components/order/quotation/OrderQuotationTable.tsx
  src/app/components/quotation/modal/QuotationModal.tsx
  src/app/components/quotation/modal/QuotationSave.tsx
  src/app/components/sign-in/SignInComponents.tsx
  src/app/components/sign-in/client/ClientComponents.tsx
  src/app/components/sign-in/client/EditClientComponents.tsx
  src/app/components/sign-in/sign-up/SignUpComponents.tsx
  src/app/constants/order.ts
  src/app/constants/styles.ts
  src/app/service/getRequest.ts
  src/app/service/patchRequest.ts
  src/app/service/postRequest.ts
  src/app/ui/Icons/Camera.tsx
  src/app/utils/callApi.ts
  src/app/utils/formatPrice.ts
  src/app/utils/saveImage.ts
  src/app/utils/setTokens.ts
Labels: feat, 현중

#25 :recycle: [메인] : 메인페이지 UI변경 api연결
  package-lock.json
  package.json
  public/Images/tomato.png
  src/app/_types/main.ts
  src/app/components/common/HeaderSearchBar.tsx
  src/app/components/common/Icons.tsx
  src/app/components/common/ProfileDropDown.tsx
  src/app/components/common/layout/Header.tsx
  src/app/components/main/Information.tsx/Announcement.tsx
  src/app/components/main/Information.tsx/CustomerService.tsx
  src/app/components/main/Information.tsx/Question.tsx
  src/app/components/main/LoginModal.tsx
  src/app/components/main/Reorder.tsx
  src/app/components/main/Welcome.tsx
  src/app/components/main/calendar/OrderCalendar.tsx
  src/app/components/main/container/InformationContainer.tsx
  src/app/components/main/container/MainContainer.tsx
  src/app/components/main/recommend/Card.tsx
  src/app/components/main/recommend/CardSwiper.tsx
  src/app/components/main/recommend/LoginModal.tsx
  src/app/components/main/recommend/Recommend.tsx
  src/app/components/main/reorder/Reorder.tsx
  src/app/components/quotation/QuotationViewTable.tsx
  src/app/constants/common.ts
  src/app/constants/main.ts
  src/app/constants/styles.ts
  src/app/constants/test.ts
  src/app/ui/Calendar.css
  src/app/ui/Icons/CalendarNext.tsx
  src/app/ui/Icons/CalendarPrev.tsx
  src/app/ui/globals.css
  src/app/ui/iconPath.ts
Labels: 민규, recycle

#27 ♻️ [상품주문] : 상품주문 페이지 UI 및 기능 수정
  src/app/(route)/admin/page.tsx
  src/app/_types/admin.ts
  src/app/api/admin/clients/[client_id]/check/route.ts
  src/app/api/admin/clients/[client_id]/comment/route.ts
  src/app/api/admin/clients/[client_id]/delete/route.ts
  src/app/api/admin/clients/[client_id]/quotations/date/route.ts
  src/app/api/admin/clients/[client_id]/quotations/route.ts
  src/app/api/admin/clients/[client_id]/region/route.ts
  src/app/api/admin/clients/name/[name]/route.ts
  src/app/api/admin/clients/region/route.ts
  src/app/api/admin/products/[product_id]/delete/route.ts
  src/app/api/admin/products/[product_id]/update/route.ts
  src/app/api/admin/products/[product_id]/vegetable/route.ts
  src/app/api/admin/products/category/[category]/route.ts
  src/app/api/admin/products/route.ts
  src/app/api/admin/products/upload/route.ts
  src/app/api/admin/products/vegetable/file/route.ts
  src/app/api/admin/quotations/extract/[quotation_id]/route.ts
  src/app/api/admin/quotations/extracts/today/route.ts
  src/app/api/admin/quotations/search/info/route.ts
  src/app/components/admin/AdminHeader.tsx
  src/app/components/admin/clients/CheckQuotation.tsx
  src/app/components/admin/clients/ClientsName.tsx
  src/app/components/admin/clients/ClientsRegion.tsx
  src/app/components/admin/clients/DeleteClient.tsx
  src/app/components/admin/clients/InquiryPastOrder.tsx
  src/app/components/admin/clients/InquiryQuotation.tsx
  src/app/components/admin/clients/InquiryQuotationDate.tsx
  src/app/components/admin/clients/SetComment.tsx
  src/app/components/admin/clients/SetRegion.tsx
  src/app/components/admin/container/ClientContainer.tsx
  src/app/components/admin/container/ProductsContainer.tsx
  src/app/components/admin/container/QuotationContainer.tsx
  src/app/components/admin/products/ProductsCategory.tsx
  src/app/components/admin/products/ProductsCreate.tsx
  src/app/components/admin/products/ProductsDelete.tsx
  src/app/components/admin/products/ProductsUpdate.tsx
  src/app/components/admin/products/ProductsUpload.tsx
  src/app/components/admin/products/ProductsVegetable.tsx
  src/app/components/admin/products/ProductsVegetableFile.tsx
  src/app/components/admin/quotations/Extract.tsx
  src/app/components/admin/quotations/ExtractToday.tsx
  src/app/components/admin/quotations/Info.tsx
  src/app/components/common/Button.tsx
  src/app/constants/admin.ts
  src/app/service/deleteRequest.ts
  src/app/service/getRequest.ts
  src/app/service/patchRequest.ts
  src/app/service/postRequest.ts
  src/app/service/putRequest.ts
  src/app/ui/globals.css
  src/app/utils/callApi.ts
Labels: 현중, recycle

#29 ♻️ [견적서] : 조회, 견적서모달 UI수정
  .eslintrc.json
  src/app/(route)/order/page.tsx
  src/app/(route)/quotation/page.tsx
  src/app/_types/order.ts
  src/app/_types/quotation.ts
  src/app/api/order/quotations/[quotation_id]/[product_id]/delete/route.ts
  src/app/api/quotation/delete/product/route.ts
  src/app/api/quotation/route.ts
  src/app/components/admin/clients/InquiryQuotation.tsx
  src/app/components/common/Pagination.tsx
  src/app/components/common/ProfileDropDown.tsx
  src/app/components/common/layout/Footer.tsx
  src/app/components/common/layout/Header.tsx
  src/app/components/common/layout/SideNavBar.tsx
  src/app/components/main/calendar/OrderCalendar.tsx
  src/app/components/main/container/MainContainer.tsx
  src/app/components/main/recommend/CardSwiper.tsx
  src/app/components/order/container/OrderContainer.tsx
  src/app/components/quotation/QuotationCalendar.tsx
  src/app/components/quotation/QuotationViewTable.tsx
  src/app/components/quotation/QuotationViewTableInfo.tsx
  src/app/components/quotation/container/EditQuoteContainer.tsx
  src/app/components/quotation/container/QuotationContainer.tsx
  src/app/components/quotation/modal/DeleteQuotationModal.tsx
  src/app/components/quotation/modal/QuotationModal.tsx
  src/app/components/quotation/modal/QuotationTable.tsx
  src/app/components/quotation/modal/edit/DeleteQuotationModal.tsx
  src/app/components/quotation/modal/edit/EditQuotationModal.tsx
  src/app/components/quotation/modal/view/QuotationModal.tsx
  src/app/components/quotation/modal/view/QuotationOrderTable.tsx
  src/app/components/quotation/modal/view/QuotationTable.tsx
  src/app/components/quotation/modal/view/QuoteBottom.tsx
  src/app/constants/common.ts
  src/app/constants/order.ts
  src/app/constants/quotation.ts
  src/app/constants/styles.ts
  src/app/service/deleteRequest.ts
  src/app/service/getRequest.ts
  src/app/ui/Calendar_small.css
  src/app/ui/Icons/CalendarNext.tsx
  src/app/ui/Icons/CalendarPrev.tsx
  src/app/ui/globals.css
  src/app/ui/iconPath.ts
  src/app/utils/date.ts
Labels: 민규, recycle

#30 도커 파일생성
  .github/workflows/nextjs.yml
  Dockerfile
Labels: feat, 민규

#35 ✨[관리자]: 기능 수정
  package-lock.json
  package.json
  src/app/(route)/admin/page.tsx
  src/app/(route)/layout.tsx
  src/app/_types/admin.ts
  src/app/api/admin/products/upload/route.ts
  src/app/api/admin/products/vegetable/file/route.ts
  src/app/api/order/quotations/products/route.ts
  src/app/components/admin/AdminHeader.tsx
  src/app/components/admin/clients/CheckQuotation.tsx
  src/app/components/admin/clients/ClientsName.tsx
  src/app/components/admin/clients/ClientsRegion.tsx
  src/app/components/admin/clients/DeleteClient.tsx
  src/app/components/admin/clients/InquiryPastOrder.tsx
  src/app/components/admin/clients/InquiryQuotation.tsx
  src/app/components/admin/clients/InquiryQuotationDate.tsx
  src/app/components/admin/clients/SetComment.tsx
  src/app/components/admin/clients/SetRegion.tsx
  src/app/components/admin/container/ClientContainer.tsx
  src/app/components/admin/container/ProductsContainer.tsx
  src/app/components/admin/notices/NoticeGet.tsx
  src/app/components/admin/notices/NoticePost.tsx
  src/app/components/admin/products/ProductsCategory.tsx
  src/app/components/admin/products/ProductsCreate.tsx
  src/app/components/admin/products/ProductsDelete.tsx
  src/app/components/admin/products/ProductsUpdate.tsx
  src/app/components/admin/products/ProductsUpload.tsx
  src/app/components/admin/products/ProductsVegetable.tsx
  src/app/components/admin/products/ProductsVegetableFile.tsx
  src/app/components/admin/quotations/Info.tsx
  src/app/components/common/useProvider.tsx
  src/app/components/main/reorder/Reorder.tsx
  src/app/components/quotation/modal/view/QuotationModal.tsx
  src/app/components/quotation/modal/view/QuotationOrderTable.tsx
  src/app/components/quotation/modal/view/QuotationTable.tsx
  src/app/components/sign-in/SignInComponents.tsx
  src/app/constants/admin.ts
  src/app/constants/order.ts
  src/app/hooks/useUser.ts
  src/app/service/patchRequest.ts
  src/app/service/postRequest.ts
  src/app/service/putRequest.ts
  src/app/store/useStore.ts
  src/app/ui/globals.css
  src/app/utils/callApi.ts
Labels: feat, 현중, recycle

#37 ✨ [메인,상품] : 견적서통계 연결, 상품조회 페이지 제작
  package-lock.json
  package.json
  src/app/(route)/product/error.tsx
  src/app/(route)/product/page.tsx
  src/app/_types/custom.ts
  src/app/_types/icon.ts
  src/app/_types/main.ts
  src/app/_types/pastorder.ts
  src/app/_types/prodcuts.ts
  src/app/_types/quotation.ts
  src/app/api/product/delete/route.ts
  src/app/api/product/get/[product_id]/route.ts
  src/app/api/product/get/route.ts
  src/app/api/product/post/bulk/route.ts
  src/app/api/product/post/route.ts
  src/app/api/product/put/[product_id]/route.ts
  src/app/api/quotation/daily/route.ts
  src/app/components/admin/container/FAQContainer.tsx
  src/app/components/admin/faq/FAQGet.tsx
  src/app/components/admin/faq/FAQPost.tsx
  src/app/components/admin/faq/FAQPut.tsx
  src/app/components/admin/notices/NoticePut.tsx
  src/app/components/common/HeaderSearchBar.tsx
  src/app/components/common/ProfileDropDown.tsx
  src/app/components/common/layout/Header.tsx
  src/app/components/common/useProvider.tsx
  src/app/components/main/Information.tsx/CustomerService.tsx
  src/app/components/main/calendar/CalendarStatus.tsx
  src/app/components/main/calendar/OrderCalendar.tsx
  src/app/components/main/recommend/Card.tsx
  src/app/components/main/recommend/CardSwiper.tsx
  src/app/components/main/reorder/Reorder.tsx
  src/app/components/order/Search.tsx
  src/app/components/pastorder/PastOrderDetail.tsx
  src/app/components/pastorder/PastOrderEdit.tsx
  src/app/components/pastorder/PastOrderTableInfo.tsx
  src/app/components/pastorder/PastorderTable.tsx
  src/app/components/pastorder/container/PastorderContainer.tsx
  src/app/components/product/ProductCard.tsx
  src/app/components/product/ProductHeader.tsx
  src/app/components/product/ProductsTable.tsx
  src/app/components/product/container/ProductContainer.tsx
  src/app/constants/common.ts
  src/app/constants/custom.ts
  src/app/constants/main.ts
  src/app/constants/pastorder.ts
  src/app/constants/product.ts
  src/app/constants/quotation.ts
  src/app/constants/styles.ts
  src/app/service/deleteRequest.ts
  src/app/service/getRequest.ts
  src/app/service/postRequest.ts
  src/app/service/putRequest.ts
  src/app/store/useStore.ts
  src/app/ui/Calendar.css
  src/app/ui/iconPath.ts
Labels: feat, 민규

#39 ✨[로그인, 가입, 헤더 견적서]: UI 수정
  public/Images/kakao_login.png
  public/Images/kakao_login_large_wide.png
  src/app/(route)/page.tsx
  src/app/(route)/sign-in/auth/page.tsx
  src/app/(route)/sign-in/client/edit/page.tsx
  src/app/(route)/sign-in/client/page.tsx
  src/app/(route)/sign-in/layout.tsx
  src/app/(route)/sign-in/page.tsx
  src/app/(route)/sign-in/sign-up/page.tsx
  src/app/_types/order.ts
  src/app/_types/sign-in.ts
  src/app/api/sign-in/kakao-login/route.ts
  src/app/components/admin/AdminHeader.tsx
  src/app/components/admin/clients/ClientsRegion.tsx
  src/app/components/common/ProfileDropDown.tsx
  src/app/components/common/layout/Header.tsx
  src/app/components/main/container/MainContainer.tsx
  src/app/components/order/container/OrderContainer.tsx
  src/app/components/order/quotation/OrderQuotationModal.tsx
  src/app/components/pastorder/PastorderTable.tsx
  src/app/components/quotation/QuotationViewTable.tsx
  src/app/components/quotation/modal/edit/EditQuotationModal.tsx
  src/app/components/quotation/modal/view/QuotationModal.tsx
  src/app/components/quotation/modal/view/QuotationOrderTable.tsx
  src/app/components/sign-in/SignInComponents.tsx
  src/app/components/sign-in/SignInSubTab.tsx
  src/app/components/sign-in/client/ClientComponents.tsx
  src/app/components/sign-in/client/EditClientComponents.tsx
  src/app/components/sign-in/common/SignInButton.tsx
  src/app/components/sign-in/common/SignInInput.tsx
  src/app/components/sign-in/sign-up/SignUpComponents.tsx
  src/app/constants/common.ts
  src/app/constants/order.ts
  src/app/constants/sign-in.ts
  src/app/constants/styles.ts
  src/app/hooks/usePastOrder.ts
  src/app/ui/globals.css
  tailwind.config.ts
Labels: feat, 현중, recycle
